Numpy 2.0 compatibility (#2027)
* change `np.Inf` to `np.inf`

AttributeError: `np.Inf` was removed in the NumPy 2.0 release. Use `np.inf` instead.

* change `np.NaN` to `np.nan`

AttributeError: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.

* fix np.uint8 range issue

OverflowError: Python integer 450 out of bounds for uint8

* use `scipy.integrate.trapezoid` instead of `np.trapz`

DeprecationWarning: `trapz` is deprecated. Use `trapezoid` instead, or one of the numerical integration functions in `scipy.integrate`.

* advance minimum scipy from 1.5 to 1.6 for integrate.trapezoid

* whatsnew PR number